// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2jtV5ahnDjl0Qr3Cby0fdqPZBQTTRCA',
    appId: '1:903089532971:web:4283bb5909bfb69cf1fa6e',
    messagingSenderId: '903089532971',
    projectId: 'loginandsignup-259ce',
    authDomain: 'loginandsignup-259ce.firebaseapp.com',
    storageBucket: 'loginandsignup-259ce.appspot.com',
    measurementId: 'G-CBCK2RJ0MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-berC7osXkWDFPNTRBM79DKlVhWUVDFE',
    appId: '1:903089532971:android:946897b3a883de10f1fa6e',
    messagingSenderId: '903089532971',
    projectId: 'loginandsignup-259ce',
    storageBucket: 'loginandsignup-259ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIepAPNtTac3Di7wjQPEjvWiPPOHlwbSs',
    appId: '1:903089532971:ios:91903fd08fe5ba83f1fa6e',
    messagingSenderId: '903089532971',
    projectId: 'loginandsignup-259ce',
    storageBucket: 'loginandsignup-259ce.appspot.com',
    iosBundleId: 'com.example.loginandsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIepAPNtTac3Di7wjQPEjvWiPPOHlwbSs',
    appId: '1:903089532971:ios:91903fd08fe5ba83f1fa6e',
    messagingSenderId: '903089532971',
    projectId: 'loginandsignup-259ce',
    storageBucket: 'loginandsignup-259ce.appspot.com',
    iosBundleId: 'com.example.loginandsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF2jtV5ahnDjl0Qr3Cby0fdqPZBQTTRCA',
    appId: '1:903089532971:web:4cdbfb74577a1dccf1fa6e',
    messagingSenderId: '903089532971',
    projectId: 'loginandsignup-259ce',
    authDomain: 'loginandsignup-259ce.firebaseapp.com',
    storageBucket: 'loginandsignup-259ce.appspot.com',
    measurementId: 'G-ZDL4Y35JT3',
  );
}
